# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20160320_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='japanese_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='primary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_type', to='pokedex.Type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='secondary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_type', to='pokedex.Type'),
        ),
    ]
