# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20160320_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite_image',
            field=models.ImageField(default='Null', upload_to='sprites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sugimori_image',
            field=models.ImageField(default='Null', upload_to='sugimori'),
            preserve_default=False,
        ),
    ]
